OPTIONS COMPRESS = YES 
		REUSE = YES
		OBS = MAX;

LIBNAME RET_BL "/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/RETIRADAS/VELOX";
LIBNAME RET_TV "/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/RETIRADAS/TV";
LIBNAME RET_FIXO "/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/RETIRADAS/FIXO";
LIBNAME PLANTA "/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/PLNT/FIXO_BL_TV";
LIBNAME DANIELLE "/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/AD_HOC/DANIELLE";

/*////////////////////PLANTAS até M-1////////////////////*/

%let anomes = 201810;

/*** PARÂMETROS MÊS ***/

%macro parametros_anomes;
	%let j=%sysfunc(putn(&anomes,z6.));
	%let p=%sysfunc(mdy(%sysfunc(substr(&j,5,2)),1,%sysfunc(substr(&j,1,4))));
	%let h=%sysfunc(mdy(%sysfunc(substr(&j,5,2)),1,%sysfunc(substr(&j,1,4))));
		%do m=0 %to 9 %by 1;
			%global h&m. p&m. hdi&m hdm&m. hdf&m. pdi&m. pdm&m. pdf&m.; 
			data _null_;
			call symput("h&m.", put(intnx("month", &h., -&m.), yymmn6.));
			call symput("p&m.", put(intnx("month", &p., +&m.), yymmn6.));

			call symput("hdi&m.", intnx("month", &h., -&m.));
			call symput("hdm&m.", intnx("day",intnx("month", &h., -&m.),+14));
			call symput("hdf&m.", intnx("day",intnx("month", &h., +1 -&m.),-1));

			call symput("pdi&m.", intnx("month", &p., +&m.));
			call symput("pdm&m.", intnx("day",intnx("month", &p., +&m.),+14));
			call symput("pdf&m.", intnx("day",intnx("month", &p., +1 +&m.),-1));
			run;
		%end;
		%do m=0 %to 9;
			%put &&h&m.;
			%put &&hdi&m.;
			%put &&hdm&m.;
			%put &&hdf&m.;
			%put &&p&m.;
			%put &&pdi&m.;
			%put &&pdm&m.;
			%put &&pdf&m.;
		%end;

%mend parametros_anomes;
%parametros_anomes

DATA DANIELLE.PLANTA_FX_BL_TV_OIT_201812;
SET PLANTA.PLANTA_FX_BL_TV_OIT_201812_T;

INFORMAT FAIXA_TEMPO_BASE_FIXO_II $20.;
	IF TEMPO_BASE_FIXO =. THEN  FAIXA_TEMPO_BASE_FIXO_II = ''; ELSE
	IF TEMPO_BASE_FIXO >= 0 AND TEMPO_BASE_FIXO <= 3 THEN FAIXA_TEMPO_BASE_FIXO_II = '0_M0aM3'; ELSE
	IF TEMPO_BASE_FIXO > 3 AND TEMPO_BASE_FIXO <= 8 THEN  FAIXA_TEMPO_BASE_FIXO_II = '1_M4aM8'; ELSE
	IF TEMPO_BASE_FIXO > 8 AND TEMPO_BASE_FIXO <= 13 THEN  FAIXA_TEMPO_BASE_FIXO_II = '2_M9aM13'; ELSE
	IF TEMPO_BASE_FIXO > 13 AND TEMPO_BASE_FIXO <= 24 THEN  FAIXA_TEMPO_BASE_FIXO_II = '3_M14aM24'; ELSE
	IF TEMPO_BASE_FIXO > 24 THEN  FAIXA_TEMPO_BASE_FIXO_II = '4_2Anos+'; ELSE
	FAIXA_TEMPO_BASE_FIXO_II='4_2Anos+';

INFORMAT FAIXA_TEMPO_BASE_BL_II $20.;
	IF TEMPO_BASE_BL =. THEN  FAIXA_TEMPO_BASE_BL_II = ''; ELSE
	IF TEMPO_BASE_BL >= 0 AND TEMPO_BASE_BL <= 3 THEN FAIXA_TEMPO_BASE_BL_II = '0_M0aM3'; ELSE
	IF TEMPO_BASE_BL > 3 AND TEMPO_BASE_BL <= 8 THEN  FAIXA_TEMPO_BASE_BL_II = '1_M4aM8'; ELSE
	IF TEMPO_BASE_BL > 8 AND TEMPO_BASE_BL <= 13 THEN  FAIXA_TEMPO_BASE_BL_II = '2_M9aM13'; ELSE
	IF TEMPO_BASE_BL > 13 AND TEMPO_BASE_BL <= 24 THEN  FAIXA_TEMPO_BASE_BL_II = '3_M14aM24'; ELSE
	IF TEMPO_BASE_BL > 24 THEN  FAIXA_TEMPO_BASE_BL_II = '4_2Anos+'; ELSE
	FAIXA_TEMPO_BASE_BL_II='4_2Anos+';

INFORMAT FAIXA_TEMPO_BASE_TV_II $20.;
	IF TEMPO_BASE_TV =. THEN  FAIXA_TEMPO_BASE_TV_II = ''; ELSE
	IF TEMPO_BASE_TV >= 0 AND TEMPO_BASE_TV <= 3 THEN FAIXA_TEMPO_BASE_TV_II = '0_M0aM3'; ELSE
	IF TEMPO_BASE_TV > 3 AND TEMPO_BASE_TV <= 8 THEN  FAIXA_TEMPO_BASE_TV_II = '1_M4aM8'; ELSE
	IF TEMPO_BASE_TV > 8 AND TEMPO_BASE_TV <= 13 THEN  FAIXA_TEMPO_BASE_TV_II = '2_M9aM13'; ELSE
	IF TEMPO_BASE_TV > 13 AND TEMPO_BASE_TV <= 24 THEN  FAIXA_TEMPO_BASE_TV_II = '3_M14aM24'; ELSE
	IF TEMPO_BASE_TV > 24 THEN  FAIXA_TEMPO_BASE_TV_II = '4_2Anos+'; ELSE
	FAIXA_TEMPO_BASE_TV_II='4_2Anos+';

INFORMAT FAIXA_TEMPO_BASE_OIT_II $20.;
	IF TEMPO_BASE_OIT =. THEN  FAIXA_TEMPO_BASE_OIT_II = ''; ELSE
	IF TEMPO_BASE_OIT >= 0 AND TEMPO_BASE_OIT <= 3 THEN FAIXA_TEMPO_BASE_OIT_II = '0_M0aM3'; ELSE
	IF TEMPO_BASE_OIT > 3 AND TEMPO_BASE_OIT <= 8 THEN  FAIXA_TEMPO_BASE_OIT_II = '1_M4aM8'; ELSE
	IF TEMPO_BASE_OIT > 8 AND TEMPO_BASE_OIT <= 13 THEN  FAIXA_TEMPO_BASE_OIT_II = '2_M9aM13'; ELSE
	IF TEMPO_BASE_OIT > 13 AND TEMPO_BASE_OIT <= 24 THEN  FAIXA_TEMPO_BASE_OIT_II = '3_M14aM24'; ELSE
	IF TEMPO_BASE_OIT > 24 THEN  FAIXA_TEMPO_BASE_OIT_II = '4_2Anos+'; ELSE
	FAIXA_TEMPO_BASE_OIT_II='4_2Anos+';

RUN;

%MACRO REF (MES);

/*PLANTA M-1*/

DATA PLANTA_FX_BL_TV_OIT_&MES.;
SET  PLANTA.PLANTA_FX_BL_TV_OIT_&MES._T (KEEP=ANOMES_PLANTA ALONE_OIT_FINAL POSSE_GERENCIAL_RESIDENCIAL POSSE_GERENCIAL_COMPLETA FAIXA_TEMPO_BASE_FIXO FAIXA_TEMPO_BASE_BL FAIXA_TEMPO_BASE_TV FAIXA_TEMPO_BASE_OIT QTD_UGR);
RUN;

/*EMPILHA RETIRADAS*/

PROC APPEND BASE = PLANTA_FX_BL_TV_OIT_FULL DATA = PLANTA_FX_BL_TV_OIT_&MES.;
SYSECHO "EMPILHA &MES.";

RUN;

%MEND REF;
%REF(201812);
%REF(201901);
%REF(201902);
%REF(201903);
%REF(201904);
%REF(201905);
%REF(201906);
%REF(&H2.);
%REF(&H1.);
%REF(&H0.);

/*TRATAMENTO DOS DADOS*/

DATA PLANTA_FX_BL_TV_OIT_FULL;
SET  
/*PLANTA.PLANTA_FX_BL_TV_OIT_201712_T
PLANTA.PLANTA_FX_BL_TV_OIT_201801_T
PLANTA.PLANTA_FX_BL_TV_OIT_201802_T
PLANTA.PLANTA_FX_BL_TV_OIT_201803_T
PLANTA.PLANTA_FX_BL_TV_OIT_201804_T
PLANTA.PLANTA_FX_BL_TV_OIT_201805_T
PLANTA.PLANTA_FX_BL_TV_OIT_201806_T
PLANTA.PLANTA_FX_BL_TV_OIT_201807_T
PLANTA.PLANTA_FX_BL_TV_OIT_201808_T
PLANTA.PLANTA_FX_BL_TV_OIT_201809_T
PLANTA.PLANTA_FX_BL_TV_OIT_201810_T
PLANTA.PLANTA_FX_BL_TV_OIT_201811_T*/
PLANTA.PLANTA_FX_BL_TV_OIT_201812_T
PLANTA.PLANTA_FX_BL_TV_OIT_201901_T
PLANTA.PLANTA_FX_BL_TV_OIT_201902_T
PLANTA.PLANTA_FX_BL_TV_OIT_201903_T
PLANTA.PLANTA_FX_BL_TV_OIT_201904_T
PLANTA.PLANTA_FX_BL_TV_OIT_201905_T
PLANTA.PLANTA_FX_BL_TV_OIT_201906_T
(KEEP=ANOMES_PLANTA ALONE_OIT_FINAL POSSE_GERENCIAL_RESIDENCIAL POSSE_GERENCIAL_COMPLETA FAIXA_TEMPO_BASE_FIXO FAIXA_TEMPO_BASE_BL FAIXA_TEMPO_BASE_TV FAIXA_TEMPO_BASE_OIT QTD_UGR);
RUN;

PROC SQL;
   CREATE TABLE WORK.PLANTA_FINAL_FULL AS 
   SELECT t1.ANOMES_PLANTA, 
          t1.ALONE_OIT_FINAL, 
		  t1.POSSE_GERENCIAL_COMPLETA,
          t1.POSSE_GERENCIAL_RESIDENCIAL, 
          t1.FAIXA_TEMPO_BASE_FIXO, 
          t1.FAIXA_TEMPO_BASE_BL, 
          t1.FAIXA_TEMPO_BASE_TV, 
          t1.FAIXA_TEMPO_BASE_OIT, 
          /* SUM_of_QTD_UGR */
            (SUM(t1.QTD_UGR)) AS SUM_of_QTD_UGR
      FROM WORK.PLANTA_FX_BL_TV_OIT_FULL t1
      GROUP BY t1.ANOMES_PLANTA,
               t1.ALONE_OIT_FINAL,
			   t1.POSSE_GERENCIAL_COMPLETA,
               t1.POSSE_GERENCIAL_RESIDENCIAL,
               t1.FAIXA_TEMPO_BASE_FIXO,
               t1.FAIXA_TEMPO_BASE_BL,
               t1.FAIXA_TEMPO_BASE_TV,
               t1.FAIXA_TEMPO_BASE_OIT;
QUIT;

/*////////////////////Retiradas////////////////////*/

%let anomes = 201811;

/*** PARÂMETROS MÊS ***/
%macro parametros_anomes;
	%let j=%sysfunc(putn(&anomes,z6.));
	%let p=%sysfunc(mdy(%sysfunc(substr(&j,5,2)),1,%sysfunc(substr(&j,1,4))));
	%let h=%sysfunc(mdy(%sysfunc(substr(&j,5,2)),1,%sysfunc(substr(&j,1,4))));
		%do m=0 %to 10 %by 1;
			%global h&m. p&m. hdi&m hdm&m. hdf&m. pdi&m. pdm&m. pdf&m.; 
			data _null_;
			call symput("h&m.", put(intnx("month", &h., -&m.), yymmn6.));
			call symput("p&m.", put(intnx("month", &p., +&m.), yymmn6.));

			call symput("hdi&m.", intnx("month", &h., -&m.));
			call symput("hdm&m.", intnx("day",intnx("month", &h., -&m.),+14));
			call symput("hdf&m.", intnx("day",intnx("month", &h., +1 -&m.),-1));

			call symput("pdi&m.", intnx("month", &p., +&m.));
			call symput("pdm&m.", intnx("day",intnx("month", &p., +&m.),+14));
			call symput("pdf&m.", intnx("day",intnx("month", &p., +1 +&m.),-1));
			run;
		%end;
		%do m=0 %to 10;
			%put &&h&m.;
			%put &&hdi&m.;
			%put &&hdm&m.;
			%put &&hdf&m.;
			%put &&p&m.;
			%put &&pdi&m.;
			%put &&pdm&m.;
			%put &&pdf&m.;
		%end;

%mend parametros_anomes;
%parametros_anomes

%MACRO REF (MES);

/*FIXO*/

DATA RET_FIXO_&MES.;
SET  RET_FIXO.RET_FIXO_&MES. (KEEP=INDICADOR ANOMES_RETIRADA TIPO_RETIRADA TIPO_RETIRADA_I TIPO_RETIRADA_II FAIXA_TEMPO_BASE_FIXO ALONE_OIT_FINAL POSSE_GERENCIAL_RESIDENCIAL POSSE_GERENCIAL_COMPLETA QTD_RET);
RUN;

/*EMPILHA RETIRADAS*/

PROC APPEND BASE = RET_FIXO_FULL DATA= RET_FIXO_&MES.;
SYSECHO "EMPILHA &MES.";

RUN;

/*BANDA LARGA*/

DATA RET_BL_&MES.;
SET  RET_BL.RET_BL_&MES. (KEEP=INDICADOR ANOMES_RETIRADA TIPO_RETIRADA TIPO_RETIRADA_I TIPO_RETIRADA_II FAIXA_TEMPO_BASE_BL ALONE_OIT_FINAL POSSE_GERENCIAL_RESIDENCIAL POSSE_GERENCIAL_COMPLETA QTD_RET);
RUN;

/*EMPILHA RETIRADAS*/

PROC APPEND BASE = RET_BL_FULL DATA= RET_BL_&MES.;
SYSECHO "EMPILHA &MES.";

RUN;

/*TV*/

DATA RET_TV_&MES.;
SET  RET_TV.RET_TV_&MES. (KEEP=INDICADOR ANOMES_RETIRADA TIPO_RETIRADA TIPO_RETIRADA_I TIPO_RETIRADA_II FAIXA_TEMPO_BASE_TV ALONE_OIT_FINAL POSSE_GERENCIAL_RESIDENCIAL POSSE_GERENCIAL_COMPLETA QTD_RET);
RUN;

/*EMPILHA RETIRADAS*/

PROC APPEND BASE = RET_TV_FULL DATA= RET_TV_&MES.;
SYSECHO "EMPILHA &MES.";

RUN;

%MEND REF;
%REF(&H10.);
%REF(&H9.);
%REF(&H8.);
%REF(&H7.);
%REF(&H6.);
%REF(&H5.);
%REF(&H4.);
%REF(&H3.);
%REF(&H2.);
%REF(&H1.);
%REF(&H0.);

/*TRATAMENTO DOS DADOS*/
/*FIXO*/

DATA RESUL_FIXO_FULL_T;
SET 
RET_FIXO.RET_FIXO_201801
RET_FIXO.RET_FIXO_201802
RET_FIXO.RET_FIXO_201803
RET_FIXO.RET_FIXO_201804
RET_FIXO.RET_FIXO_201805
RET_FIXO.RET_FIXO_201806
RET_FIXO.RET_FIXO_201807
RET_FIXO.RET_FIXO_201808
RET_FIXO.RET_FIXO_201809
RET_FIXO.RET_FIXO_201810
RET_FIXO.RET_FIXO_201811
RET_FIXO.RET_FIXO_201812;
RUN;


PROC SQL;
   CREATE TABLE RESUL_FIXO_FULL_TT AS 
   SELECT t1.INDICADOR, 
          t1.ANOMES_RETIRADA, 
          t1.TIPO_RETIRADA, 
          t1.TIPO_RETIRADA_I, 
          t1.TIPO_RETIRADA_II, 
		  t1.FAIXA_TEMPO_BASE_FIXO,
          t1.ALONE_OIT_FINAL, 
          t1.POSSE_GERENCIAL_RESIDENCIAL, 
          /* SUM_of_QTD_RET */
            (SUM(t1.QTD_RET)) AS SUM_of_QTD_RET
      FROM RESUL_FIXO_FULL_T t1
      GROUP BY t1.INDICADOR,
               t1.ANOMES_RETIRADA,
               t1.TIPO_RETIRADA,
               t1.TIPO_RETIRADA_I,
               t1.TIPO_RETIRADA_II,
			   t1.FAIXA_TEMPO_BASE_FIXO,
               t1.ALONE_OIT_FINAL,
               t1.POSSE_GERENCIAL_RESIDENCIAL;
QUIT;

/*BANDA LARGA*/

DATA RESUL_BL_FULL_T;
SET 
RET_BL.RET_BL_201801
RET_BL.RET_BL_201802
RET_BL.RET_BL_201803
RET_BL.RET_BL_201804
RET_BL.RET_BL_201805
RET_BL.RET_BL_201806
RET_BL.RET_BL_201807
RET_BL.RET_BL_201808
RET_BL.RET_BL_201809
RET_BL.RET_BL_201810
RET_BL.RET_BL_201811
RET_BL.RET_BL_201812;
RUN;

PROC SQL;
   CREATE TABLE RESUL_BL_FULL_TT AS 
   SELECT t1.INDICADOR, 
          t1.ANOMES_RETIRADA, 
          t1.TIPO_RETIRADA, 
          t1.TIPO_RETIRADA_I, 
          t1.TIPO_RETIRADA_II, 
		  t1.FAIXA_TEMPO_BASE_BL,
          t1.ALONE_OIT_FINAL, 
          t1.POSSE_GERENCIAL_RESIDENCIAL, 
          /* SUM_of_QTD_RET */
            (SUM(t1.QTD_RET)) AS SUM_of_QTD_RET
      FROM RESUL_BL_FULL_T t1
      GROUP BY t1.INDICADOR,
               t1.ANOMES_RETIRADA,
               t1.TIPO_RETIRADA,
               t1.TIPO_RETIRADA_I,
               t1.TIPO_RETIRADA_II,
			   t1.FAIXA_TEMPO_BASE_BL,
               t1.ALONE_OIT_FINAL,
               t1.POSSE_GERENCIAL_RESIDENCIAL;
QUIT;

/*TV*/

DATA RESUL_TV_FULL_T;
SET 
RET_TV.RET_TV_201801
RET_TV.RET_TV_201802
RET_TV.RET_TV_201803
RET_TV.RET_TV_201804
RET_TV.RET_TV_201805
RET_TV.RET_TV_201806
RET_TV.RET_TV_201807
RET_TV.RET_TV_201808
RET_TV.RET_TV_201809
RET_TV.RET_TV_201810
RET_TV.RET_TV_201811
RET_TV.RET_TV_201812;
RUN;

PROC SQL;
   CREATE TABLE RESUL_TV_FULL_TT AS 
   SELECT t1.INDICADOR, 
          t1.ANOMES_RETIRADA, 
          t1.TIPO_RETIRADA, 
          t1.TIPO_RETIRADA_I, 
          t1.TIPO_RETIRADA_II, 
		  t1.FAIXA_TEMPO_BASE_TV,
          t1.ALONE_OIT_FINAL, 
          t1.POSSE_GERENCIAL_RESIDENCIAL, 
          /* SUM_of_QTD_RET */
            (SUM(t1.QTD_RET)) AS SUM_of_QTD_RET
      FROM RESUL_TV_FULL_T t1
      GROUP BY t1.INDICADOR,
               t1.ANOMES_RETIRADA,
               t1.TIPO_RETIRADA,
               t1.TIPO_RETIRADA_I,
               t1.TIPO_RETIRADA_II,
			   t1.FAIXA_TEMPO_BASE_TV,
               t1.ALONE_OIT_FINAL,
               t1.POSSE_GERENCIAL_RESIDENCIAL;
QUIT;