OPTIONS COMPRESS = YES 
		REUSE = YES
		OBS = MAX;

LIBNAME PLANTA "/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/PLNT/FIXO_BL_TV";
LIBNAME DANIELLE "/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/AD_HOC/DANIELLE";

/*------------------- PLANTAS até M-1 -------------------*/

%MACRO REF (MES);

DATA PLANTA_FX_BL_TV_OIT_&MES.;
SET  PLANTA.PLANTA_FX_BL_TV_OIT_&MES._T (KEEP=ANOMES_PLANTA ALONE_OIT_FINAL POSSE_GERENCIAL_RESIDENCIAL POSSE_GERENCIAL_COMPLETA FAIXA_TEMPO_BASE_FIXO FAIXA_TEMPO_BASE_BL FAIXA_TEMPO_BASE_TV FAIXA_TEMPO_BASE_OIT QTD_UGR);
RUN;

%MEND REF;
%REF(201812);
%REF(201901);
%REF(201902);
%REF(201903);
%REF(201904);
%REF(201905);
%REF(201906);
%REF(201907);

DATA PLANTA_FINAL_FULL;
SET 
PLANTA_FX_BL_TV_OIT_201812
PLANTA_FX_BL_TV_OIT_201901
PLANTA_FX_BL_TV_OIT_201902
PLANTA_FX_BL_TV_OIT_201903
PLANTA_FX_BL_TV_OIT_201904
PLANTA_FX_BL_TV_OIT_201905
PLANTA_FX_BL_TV_OIT_201906
PLANTA_FX_BL_TV_OIT_201907;
RUN;

/*TRATAMENTO DOS DADOS*/

PROC SQL;
   CREATE TABLE WORK.PLANTA_FINAL_FULL_II AS 
   SELECT t1.ANOMES_PLANTA, 
          t1.ALONE_OIT_FINAL, 
		  t1.POSSE_GERENCIAL_COMPLETA,
          t1.POSSE_GERENCIAL_RESIDENCIAL, 
          t1.FAIXA_TEMPO_BASE_FIXO, 
          t1.FAIXA_TEMPO_BASE_BL, 
          t1.FAIXA_TEMPO_BASE_TV, 
          t1.FAIXA_TEMPO_BASE_OIT, 
          /* SUM_of_QTD_UGR */
            (SUM(t1.QTD_UGR)) AS SUM_of_QTD_UGR
      FROM PLANTA_FINAL_FULL t1
      GROUP BY t1.ANOMES_PLANTA,
               t1.ALONE_OIT_FINAL,
			   t1.POSSE_GERENCIAL_COMPLETA,
               t1.POSSE_GERENCIAL_RESIDENCIAL,
               t1.FAIXA_TEMPO_BASE_FIXO,
               t1.FAIXA_TEMPO_BASE_BL,
               t1.FAIXA_TEMPO_BASE_TV,
               t1.FAIXA_TEMPO_BASE_OIT;
QUIT;

PROC EXPORT 
    DATA = PLANTA_FINAL_FULL_II
    OUTFILE= "/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/AD_HOC/DANIELLE/PLANTA_FINAL_BOOK.txt" 
    DBMS = TAB REPLACE;
RUN;

/*ORÇAMENTO: MUDANÇA NAS PARTIÇÕES POR AGING

DATA DANIELLE.PLANTA_FX_BL_TV_OIT_201812;
SET PLANTA.PLANTA_FX_BL_TV_OIT_201812_T;

INFORMAT FAIXA_TEMPO_BASE_FIXO_II $20.;
	IF TEMPO_BASE_FIXO =. THEN  FAIXA_TEMPO_BASE_FIXO_II = ''; ELSE
	IF TEMPO_BASE_FIXO >= 0 AND TEMPO_BASE_FIXO <= 3 THEN FAIXA_TEMPO_BASE_FIXO_II = '0_M0aM3'; ELSE
	IF TEMPO_BASE_FIXO > 3 AND TEMPO_BASE_FIXO <= 8 THEN  FAIXA_TEMPO_BASE_FIXO_II = '1_M4aM8'; ELSE
	IF TEMPO_BASE_FIXO > 8 AND TEMPO_BASE_FIXO <= 13 THEN  FAIXA_TEMPO_BASE_FIXO_II = '2_M9aM13'; ELSE
	IF TEMPO_BASE_FIXO > 13 AND TEMPO_BASE_FIXO <= 24 THEN  FAIXA_TEMPO_BASE_FIXO_II = '3_M14aM24'; ELSE
	IF TEMPO_BASE_FIXO > 24 THEN  FAIXA_TEMPO_BASE_FIXO_II = '4_2Anos+'; ELSE
	FAIXA_TEMPO_BASE_FIXO_II='4_2Anos+';

INFORMAT FAIXA_TEMPO_BASE_BL_II $20.;
	IF TEMPO_BASE_BL =. THEN  FAIXA_TEMPO_BASE_BL_II = ''; ELSE
	IF TEMPO_BASE_BL >= 0 AND TEMPO_BASE_BL <= 3 THEN FAIXA_TEMPO_BASE_BL_II = '0_M0aM3'; ELSE
	IF TEMPO_BASE_BL > 3 AND TEMPO_BASE_BL <= 8 THEN  FAIXA_TEMPO_BASE_BL_II = '1_M4aM8'; ELSE
	IF TEMPO_BASE_BL > 8 AND TEMPO_BASE_BL <= 13 THEN  FAIXA_TEMPO_BASE_BL_II = '2_M9aM13'; ELSE
	IF TEMPO_BASE_BL > 13 AND TEMPO_BASE_BL <= 24 THEN  FAIXA_TEMPO_BASE_BL_II = '3_M14aM24'; ELSE
	IF TEMPO_BASE_BL > 24 THEN  FAIXA_TEMPO_BASE_BL_II = '4_2Anos+'; ELSE
	FAIXA_TEMPO_BASE_BL_II='4_2Anos+';

INFORMAT FAIXA_TEMPO_BASE_TV_II $20.;
	IF TEMPO_BASE_TV =. THEN  FAIXA_TEMPO_BASE_TV_II = ''; ELSE
	IF TEMPO_BASE_TV >= 0 AND TEMPO_BASE_TV <= 3 THEN FAIXA_TEMPO_BASE_TV_II = '0_M0aM3'; ELSE
	IF TEMPO_BASE_TV > 3 AND TEMPO_BASE_TV <= 8 THEN  FAIXA_TEMPO_BASE_TV_II = '1_M4aM8'; ELSE
	IF TEMPO_BASE_TV > 8 AND TEMPO_BASE_TV <= 13 THEN  FAIXA_TEMPO_BASE_TV_II = '2_M9aM13'; ELSE
	IF TEMPO_BASE_TV > 13 AND TEMPO_BASE_TV <= 24 THEN  FAIXA_TEMPO_BASE_TV_II = '3_M14aM24'; ELSE
	IF TEMPO_BASE_TV > 24 THEN  FAIXA_TEMPO_BASE_TV_II = '4_2Anos+'; ELSE
	FAIXA_TEMPO_BASE_TV_II='4_2Anos+';

INFORMAT FAIXA_TEMPO_BASE_OIT_II $20.;
	IF TEMPO_BASE_OIT =. THEN  FAIXA_TEMPO_BASE_OIT_II = ''; ELSE
	IF TEMPO_BASE_OIT >= 0 AND TEMPO_BASE_OIT <= 3 THEN FAIXA_TEMPO_BASE_OIT_II = '0_M0aM3'; ELSE
	IF TEMPO_BASE_OIT > 3 AND TEMPO_BASE_OIT <= 8 THEN  FAIXA_TEMPO_BASE_OIT_II = '1_M4aM8'; ELSE
	IF TEMPO_BASE_OIT > 8 AND TEMPO_BASE_OIT <= 13 THEN  FAIXA_TEMPO_BASE_OIT_II = '2_M9aM13'; ELSE
	IF TEMPO_BASE_OIT > 13 AND TEMPO_BASE_OIT <= 24 THEN  FAIXA_TEMPO_BASE_OIT_II = '3_M14aM24'; ELSE
	IF TEMPO_BASE_OIT > 24 THEN  FAIXA_TEMPO_BASE_OIT_II = '4_2Anos+'; ELSE
	FAIXA_TEMPO_BASE_OIT_II='4_2Anos+';

RUN;